import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-light': {
          DEFAULT: 'hsl(var(--color-primary-light-500))',
          100: 'hsl(var(--color-primary-light-100))',
          200: 'hsl(var(--color-primary-light-200))',
          300: 'hsl(var(--color-primary-light-300))',
          400: 'hsl(var(--color-primary-light-400))',
          500: 'hsl(var(--color-primary-light-500))',
          600: 'hsl(var(--color-primary-light-600))',
          700: 'hsl(var(--color-primary-light-700))',
          800: 'hsl(var(--color-primary-light-800))',
          900: 'hsl(var(--color-primary-light-900))',
        },
        'primary-heavy': {
          DEFAULT: 'hsl(var(--color-primary-heavy-500))',
          100: 'hsl(var(--color-primary-heavy-100))',
          200: 'hsl(var(--color-primary-heavy-200))',
          300: 'hsl(var(--color-primary-heavy-300))',
          400: 'hsl(var(--color-primary-heavy-400))',
          500: 'hsl(var(--color-primary-heavy-500))',
          600: 'hsl(var(--color-primary-heavy-600))',
          700: 'hsl(var(--color-primary-heavy-700))',
          800: 'hsl(var(--color-primary-heavy-800))',
          900: 'hsl(var(--color-primary-heavy-900))',
        },
        'neutral-light': {
          DEFAULT: 'hsl(var(--color-neutral-light-500))',
          0: 'hsl(var(--color-neutral-light-0))',
          50: 'hsl(var(--color-neutral-light-50))',
          100: 'hsl(var(--color-neutral-light-100))',
          200: 'hsl(var(--color-neutral-light-200))',
          300: 'hsl(var(--color-neutral-light-300))',
          400: 'hsl(var(--color-neutral-light-400))',
          500: 'hsl(var(--color-neutral-light-500))',
          600: 'hsl(var(--color-neutral-light-600))',
          700: 'hsl(var(--color-neutral-light-700))',
          800: 'hsl(var(--color-neutral-light-800))',
          900: 'hsl(var(--color-neutral-light-900))',
          1000: 'hsl(var(--color-neutral-light-1000))',
        },
        'neutral-heavy': {
          DEFAULT: 'hsl(var(--color-neutral-heavy-500))',
          50: 'hsl(var(--color-neutral-heavy-50))',
          100: 'hsl(var(--color-neutral-heavy-100))',
          200: 'hsl(var(--color-neutral-heavy-200))',
          300: 'hsl(var(--color-neutral-heavy-300))',
          400: 'hsl(var(--color-neutral-heavy-400))',
          500: 'hsl(var(--color-neutral-heavy-500))',
          600: 'hsl(var(--color-neutral-heavy-600))',
          700: 'hsl(var(--color-neutral-heavy-700))',
          800: 'hsl(var(--color-neutral-heavy-800))',
          900: 'hsl(var(--color-neutral-heavy-900))',
          1000: 'hsl(var(--color-neutral-heavy-1000))',
          1100: 'hsl(var(--color-neutral-heavy-1100))',
        },
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        accent: 'hsl(var(--accent))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config
